### ISSUE TITLE
desi_pipe cleanup --submitted incorrectly moves some "done" jobs back to "ready"

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#799] opened 2019-07-21 04:04 UTC
Problem: `desi_pipe cleanup --submitted` moved some "done" jobs back into "ready", even though their outputs were on disk.

Details: I had a spectra-redshifts job that died from an out of memory error during spectral regrouping, though 287/633 of the healpixels had already finished and were marked as "done":
```
[cori12 ~] desi_pipe top --once
----------------+---------+---------+---------+---------+---------+---------+
   Task Type    | waiting | ready   | running | done    | failed  | submit  |
----------------+---------+---------+---------+---------+---------+---------+
preproc         |        0|        0|        0|     5130|        0|     5130|
psf             |        0|        0|        0|      630|        0|      630|
psfnight        |        0|        0|        0|      210|        0|      210|
traceshift      |        0|        0|        0|     4500|        0|     4500|
extract         |        0|        0|        0|     4497|        3|     4500|
fiberflat       |        0|        0|        0|      630|        0|      630|
fiberflatnight  |        0|        0|        0|      210|        0|      210|
sky             |        3|        0|        0|     3867|        0|     3870|
starfit         |        3|        0|        0|     1287|        0|     1290|
fluxcalib       |        9|        0|        0|     3861|        0|     3870|
cframe          |        9|        0|        0|     3861|        0|     3870|
spectra         |        0|        0|      346|      287|        0|       NA|
redshift        |      633|        0|        0|        0|        0|       NA|
----------------+---------+---------+---------+---------+---------+---------+
```

The corresponding output files were on disk, matching the number of "done" spectra processes:
```
[cori12 ~] find $DESI_SPECTRO_REDUX/$SPECPROD/spectra-64/ -name spectra-64\*.fits | wc -l
287
```

But when I ran `desi_pipe cleanup --submitted` it moved all of the spectra "done" tasks back to "ready", instead of only resetting the "running" tasks:
```
[cori12 ~] desi_pipe cleanup --submitted
[cori12 ~] desi_pipe top --once
----------------+---------+---------+---------+---------+---------+---------+
   Task Type    | waiting | ready   | running | done    | failed  | submit  |
----------------+---------+---------+---------+---------+---------+---------+
preproc         |        0|        0|        0|     5130|        0|        0|
psf             |        0|        0|        0|      630|        0|        0|
psfnight        |        0|        0|        0|      210|        0|        0|
traceshift      |        0|        0|        0|     4500|        0|        0|
extract         |        0|        0|        0|     4497|        3|        0|
fiberflat       |        0|        0|        0|      630|        0|        0|
fiberflatnight  |        0|        0|        0|      210|        0|        0|
sky             |        3|        0|        0|     3867|        0|        0|
starfit         |        3|        0|        0|     1287|        0|        0|
fluxcalib       |        9|        0|        0|     3861|        0|        0|
cframe          |        9|        0|        0|     3861|        0|        0|
spectra         |        0|      633|        0|        0|        0|       NA|
redshift        |      633|        0|        0|        0|        0|       NA|
----------------+---------+---------+---------+---------+---------+---------+
```

@michaeljwilson has also seen this effect.

My production is in `/global/cscratch1/sd/sjbailey/desi/svdc2019d/spectro/redux/v4` but I'm going to proceed with trying to re-process the spectra + redshifts so that won't necessarily be in a state to debug when looking at it later, though the set of input frame files might be ready for reproducing the OOM (on KNL) plus the incorrect recovery.

**Comment by michaelJwilson** [comment] 2019-07-22 18:01
desi_pipe sync exhibits the same behaviour.

**Comment by sbailey** [comment] 2019-07-22 18:43
And the same effect happens for the redshift step (not just the spectra step).

**Comment by julienguy** [comment] 2019-08-06 00:54
@sbailey 
The function `db.getready()` is probably the culprit. But it's not obvious there is any bug:

`db.getready()`  updates the state of spectra and redshift tasks depending on the `state` value of the corresponding entries in the  `healpix_frame` table (joint table of healpix and frame referenced by an exposure id). So ... even if you have a spectra task marked as "done" in the DB, it can be reset to a state "ready" if an entry from the `healpix_frame` table with the same healpix has a `state=1`. This `state` is set at the end of the processing of a cframe task, to indicate the system a new cframe is ready to be incorporated in the spectra file.
So in fact, from the description of the issue, it's not totally clear there is a bug. And it's hard to tell without an example to test. You might well have rerun the cframe tasks of your prod after a first run of spectra, I cannot tell from this.

@michaelJwilson 
This is the same situation. When you run `desi_pipe sync`, it's possible the code finds new cframe or spectra and changes the state or preexisting spectra or redshifts marked as done.

I am not saying there is no bug, just that there is not sufficient information here to be certain there is one. I am trying to test this starting from one of Mike's prod, and inspecting the db tables.

**Comment by sbailey** [comment] 2019-08-06 04:46
@julienguy from the "desi_pipe top --once" examples in the original post:
* in the starting state
  * all 3861 cframe tasks are "done" with no failures or other cframe tasks in other states.
  * the spectra tasks had crashed mid-way through with a mix of running and done states
* running "desi_pipe cleanup --submitted" moved *all* the spectra tasks back into "ready", including the done ones.  No new cframe tasks had come in, and all the cframe tasks remained "done".

So it isn't a matter of new cframe data converting a previously "done" healpix back into a "ready" state because of new data, but perhaps there is a bug in updating or querying the healpix_frame table?

We can coordinate tomorrow for how to get back into the problematic state for you to inspect the DB tables, without requiring us to rerun the entire prod from the start.

**Comment by julienguy** [comment] 2019-08-06 20:02
There was a corner case that was not handled properly:
If a spectra or redshift task was 'done' but marked as 'running' because the job did not end well, `db.cleanup` was setting it to 'waiting' , but `db.getready` was not setting it back to 'done'. 
This is supposed to be fixed in branch  desi-pipe-getready-fix , but this is not the bug reported above(!)

I don't see how 'done' spectra can be set back to 'ready' if the parent cframe tasks have not been modified ... I would need to be able to reproduce this bug.

**Comment by sbailey** [comment] 2019-08-07 16:28
This is now fixed in @julienguy branch desi-pipe-getready-fix.  When a spectra or redshift task is done, it now also updates the healpix_frame table in the same transaction rather than waiting until the end of the job (which may have crashed in the meantime).

@julienguy please do any final cleanup and proceed with a pull request.  Thanks.

```
[cori05 ~] desi_pipe top --once
----------------+---------+---------+---------+---------+---------+---------+
   Task Type    | waiting | ready   | running | done    | failed  | submit  |
----------------+---------+---------+---------+---------+---------+---------+
preproc         |        0|        0|        0|     5130|        0|        0|
psf             |        0|        0|        0|      630|        0|        0|
psfnight        |        0|        0|        0|      210|        0|        0|
traceshift      |        0|        0|        0|     4500|        0|        0|
extract         |        0|        3|        0|     4497|        0|        0|
fiberflat       |        0|        0|        0|      630|        0|        0|
fiberflatnight  |        0|        0|        0|      210|        0|        0|
sky             |        3|        0|        0|     3867|        0|        0|
starfit         |        3|        0|        0|     1287|        0|        0|
fluxcalib       |        9|        0|        0|     3861|        0|        0|
cframe          |        9|        0|        0|     3861|        0|        0|
spectra         |        0|        0|      425|      208|        0|       NA|
redshift        |      425|      208|        0|        0|        0|       NA|
----------------+---------+---------+---------+---------+---------+---------+
[cori05 ~] desi_pipe cleanup --submitted
[cori05 ~] desi_pipe top --once
----------------+---------+---------+---------+---------+---------+---------+
   Task Type    | waiting | ready   | running | done    | failed  | submit  |
----------------+---------+---------+---------+---------+---------+---------+
preproc         |        0|        0|        0|     5130|        0|        0|
psf             |        0|        0|        0|      630|        0|        0|
psfnight        |        0|        0|        0|      210|        0|        0|
traceshift      |        0|        0|        0|     4500|        0|        0|
extract         |        0|        3|        0|     4497|        0|        0|
fiberflat       |        0|        0|        0|      630|        0|        0|
fiberflatnight  |        0|        0|        0|      210|        0|        0|
sky             |        3|        0|        0|     3867|        0|        0|
starfit         |        3|        0|        0|     1287|        0|        0|
fluxcalib       |        9|        0|        0|     3861|        0|        0|
cframe          |        9|        0|        0|     3861|        0|        0|
spectra         |        0|      425|        0|      208|        0|       NA|
redshift        |      425|      208|        0|        0|        0|       NA|
----------------+---------+---------+---------+---------+---------+---------+
```

**Closed** 2019-08-07 17:53 UTC
Labels: pipeline
