### ISSUE TITLE
redmonster/zfind multiprocessing hanging

### ISSUE THREAD

**Issue by moustakas** [desihub/desispec#199] opened 2016-05-20 00:18 UTC
I don't yet have a MWE to share, but I'm having trouble running zfind/redmonster with more than one processor, i.e., with multiprocessing.  I'm running the code on my laptop (OS X) with the ```master``` branch of ```desispec```.  This has happened several different times with different inputs, so it doesn't seem to be a one-off issue.  After getting through a bunch of spectra I get a pop-up window say my Python session has crashed and my xterm just hangs (I have to suspend the job and then kill it to get back my prompt).  I've tried with anywhere between 2-4 processors (my machine has four cores). Any thoughts?

```
prometheus:trunk% python bgs-sims.py --zfind -n 1
:0: FutureWarning: IPython widgets are experimental and may change in the future.
INFO:bgs-sims.py:106:main: Reading /Users/ioannis/research/projects/desi/spectro/sim/brightsims/ztest-input.fits
INFO:zfind.py:72:main: Reading bricks
INFO:zfind.py:94:main: Filter found: r
INFO:zfind.py:94:main: Filter found: b
INFO:zfind.py:94:main: Filter found: z
INFO:zfind.py:100:main: Fitting 10 targets
INFO:zfind.py:109:main: Combining individual channels and exposures
INFO:zfind.py:167:main: starting multiprocessing with 4 cpus for 10 spectra in 4 groups
Fitting fiber 1 of 2 for template /Users/ioannis/repos/git/redmonster/templates/ndArch-ssp_em_galaxy-v000.fits
Fitting fiber 1 of 3 for template /Users/ioannis/repos/git/redmonster/templates/ndArch-ssp_em_galaxy-v000.fits
Chi^2_null value is 22636.1757253
Chi^2_null value is 7708.39409434
Fitting fiber 1 of 3 for template /Users/ioannis/repos/git/redmonster/templates/ndArch-ssp_em_galaxy-v000.fits
Chi^2_null value is 545907.381419
Fitting fiber 1 of 2 for template /Users/ioannis/repos/git/redmonster/templates/ndArch-ssp_em_galaxy-v000.fits
Chi^2_null value is 91198.3521789
Fitting fiber 2 of 2 for template /Users/ioannis/repos/git/redmonster/templates/ndArch-ssp_em_galaxy-v000.fits
Chi^2_null value is 143483.813893
Fitting fiber 2 of 3 for template /Users/ioannis/repos/git/redmonster/templates/ndArch-ssp_em_galaxy-v000.fits
Chi^2_null value is 257278.315393
Fitting fiber 2 of 2 for template /Users/ioannis/repos/git/redmonster/templates/ndArch-ssp_em_galaxy-v000.fits
Chi^2_null value is 141377.93647
Fitting fiber 2 of 3 for template /Users/ioannis/repos/git/redmonster/templates/ndArch-ssp_em_galaxy-v000.fits
Chi^2_null value is 14611.1664889
Not writing chi2
Fitting fiber 3 of 3 for template /Users/ioannis/repos/git/redmonster/templates/ndArch-ssp_em_galaxy-v000.fits
Chi^2_null value is 9267.34251991
Not writing chi2
Fitting fiber 3 of 3 for template /Users/ioannis/repos/git/redmonster/templates/ndArch-ssp_em_galaxy-v000.fits
Chi^2_null value is 106046.623762
Not writing chi2
Not writing chi2
```

**Comment by sbailey** [comment] 2016-05-20 00:28
Apologies if I'm just out of the loop, but where is the `bgs-sims.py` code and exactly how does it call the redmonster / zfind code?  If it goes via `desi_zfind` / `desispec.scripts.zfind.main()`, do you get the same error if you run with `--nproc 1`?  That turns off the multiprocessing parallelization and could help isolate if the problem is in redmonster itself or in our wrapper of it.

Are you possibly running out of memory?

**Comment by cballand** [comment] 2016-05-20 14:18
I recently ran into the same problem when running redmonster on bricks of eBOSS spectra provided by Nicolas. I was wondering whether the issue was linked to the bricks, but the fact that you also have this problem hints towards a problem with the parallelized version of red monster. desi_zfind.py crashes when the number of objects (set by the -n argument) exceeds some value. For a lower number of spectra, desi_zfind.py proceeds normally. I’m running it at NERSC on 32 procs.

**Comment by moustakas** [comment] 2016-05-20 15:31
Thanks @cballand.  The bricks I'm fitting only have 10-20 objects, so it must be something else. How can I check if I'm running out of memory, @sbailey?  And no, running ```--nproc 1``` works just fine (although it takes forever!), so it must be related to the multiprocessing.

**Comment by timahutchinson** [comment] 2016-05-20 18:28
Where would I find bgs-sims.py?

**Comment by moustakas** [comment] 2016-05-24 21:08
@timahutchinson The script is here: 
  https://desi.lbl.gov/svn/docs/technotes/spectro/bgs-sims/trunk/bgs-sims.py
However, this has only been run on my laptop.  I was working on moving (regenerating) the simulated bricks to (on) NERSC when it went down this morning.  I'll send more details tomorrow, but if you see any obvious issues with how the redmonster mp is being called please let me know.  Thanks.

**Comment by moustakas** [comment] 2016-05-26 16:15
Here are some notes on trying to debug this issue on cori.  There is also one (newbie) question about running jobs on cori that I would be grateful if someone could answer.

For now, I'm using master versions of all the relevant packages, including desisim, desispec, specsim, and redmonster.  On cori, the high-level wrapper Python script I'm trying to run can be grabbed here:
```
  svn export https://desi.lbl.gov/svn/docs/technotes/spectro/bgs-sims/trunk/bgs-sims.py
```

The set of bricks that I've already generated are here:
```
ls -l /project/projectdirs/desi/spectro/sim/bgs-sims1.0/bricks
total 12800
drwxrws---+ 2 ioannis desi 131072 May 26 06:51 sim01-000
drwxrws---+ 2 ioannis desi 131072 May 26 03:45 sim01-001
drwxrws---+ 2 ioannis desi 131072 May 26 03:46 sim01-002
drwxrws---+ 2 ioannis desi 131072 May 26 03:46 sim01-003
drwxrws---+ 2 ioannis desi 131072 May 26 03:46 sim01-004
drwxrws---+ 2 ioannis desi 131072 May 26 03:46 sim01-005
drwxrws---+ 2 ioannis desi 131072 May 26 03:46 sim01-006
drwxrws---+ 2 ioannis desi 131072 May 26 03:47 sim01-007
drwxrws---+ 2 ioannis desi 131072 May 26 03:47 sim01-008
drwxrws---+ 2 ioannis desi 131072 May 26 03:47 sim01-009
drwxrws---+ 2 ioannis desi 131072 May 26 03:47 sim01-010
[snip]
```
There are a total of 50 bricks in "sim01" (simulation 1).  The python script has been hard-coded to test on just one of these bricks (each containing just 20 spectra).  

Next, I request 8 cores in the debugging queue and submit the job using ```srun```:
```
salloc -n 8 -p debug -L project
srun python bgs-sims.py --sim 1 --nproc 8 --zfind
```
[Question: do I need to specify ```-n 8``` in ```salloc``` or can I just do it in ```srun```?  For example, can I do
```
salloc -N 1 -p debug -L project
srun -n 8 python bgs-sims.py --sim 1 --nproc 8 --zfind
```
since for this particular test I don't expect to use more than 64 cores (i.e., more than 1 node)?  And of course I need to make sure that my ```nproc``` optional input and ```-n``` are consistent.]

After a couple minutes of waiting (presumably waiting for python to start -- I don't know), the code successfully finishes, in under a minute (I'm only exploring two template types---ELG,LRG---over a limited redshift range, 0.1-0.3, so things are fast).  

So---based on this test at least---I can't reproduce the hanging multiprocessing that I was getting on my laptop (although @cballand's experience perhaps suggests otherwise).  @timahutchinson Any thoughts?

However, there's one more issue I've just noticed:  The output ```zbest``` file does not seem to be row-matched to the input brick file!  To wit:
```
import numpy as np
from pprint import pprint
from astropy.io import fits
zz = fits.getdata('/project/projectdirs/desi/spectro/sim/bgs-sims1.0/bricks/sim01-010/zbest-sim01-010.fits', 1)
tt = fits.getdata('/project/projectdirs/desi/spectro/sim/bgs-sims1.0/bricks/sim01-010/truth-brick-r-sim01-010.fits', 2)
pprint(zip(tt['targetid'], zz['targetid']))
[(3121986842557655458, 3121986842557655458),
 (2558302896043269815, 3825873694579816059),
 (2134660420265421879, 118032496576090747),
 (3421799363804980172, 2381713562852533999),
 (2113542537137025845, 922438194897301927),
 (449509147632020509, 2558302896043269815),
 (393303370626957140, 3421799363804980172),
 (4469951429904521973, 4164953062623007117),
 (3637187583903263295, 3074282867501301373),
 (3825873694579816059, 2869543938800671441),
 (118032496576090747, 3896407669070591891),
 (922438194897301927, 393303370626957140),
 (3896407669070591891, 2113542537137025845),
 (3074282867501301373, 2134660420265421879),
 (3955664727431422967, 793621302138915492),
 (4164953062623007117, 4563662158207646786),
 (2381713562852533999, 3637187583903263295),
 (2869543938800671441, 3955664727431422967),
 (4563662158207646786, 449509147632020509),
 (793621302138915492, 4469951429904521973)]
pprint(zip(tt['truez'], zz['z']))
[(0.1600011, 0.16020592675321535),
 (0.24224494, 0.18222965193816845),
 (0.28333145, 0.1263221034931665),
 (0.29288739, 0.29179598321992201),
 (0.29515651, 0.12284307441825021),
 (0.12582259, 0.24237469220832272),
 (0.28111166, 0.29278371019098959),
 (0.19947933, 0.18235826711360362),
 (0.20860445, 0.28315708232399034),
 (0.18227899, 0.20198055915787946),
 (0.12620908, 0.24953231129767209),
 (0.12270356, 0.28111089348925472),
 (0.24947461, 0.29521506113109458),
 (0.28315413, 0.28338304857191904),
 (0.1794076, 0.14489143277794411),
 (0.18237491, 0.29326234416036073),
 (0.2917459, 0.20870039565569934),
 (0.20209132, 0.17942034065259632),
 (0.29338408, 0.12586581425395646),
 (0.14491387, 0.19955498210740999)]
pprint(zip(tt['truez'][np.argsort(tt['targetid'])], zz['z'][np.argsort(zz['targetid'])]))
[(0.12620908, 0.1263221034931665),
 (0.28111166, 0.28111089348925472),
 (0.12582259, 0.12586581425395646),
 (0.14491387, 0.14489143277794411),
 (0.12270356, 0.12284307441825021),
 (0.29515651, 0.29521506113109458),
 (0.28333145, 0.28338304857191904),
 (0.2917459, 0.29179598321992201),
 (0.24224494, 0.24237469220832272),
 (0.20209132, 0.20198055915787946),
 (0.28315413, 0.28315708232399034),
 (0.1600011, 0.16020592675321535),
 (0.29288739, 0.29278371019098959),
 (0.20860445, 0.20870039565569934),
 (0.18227899, 0.18222965193816845),
 (0.24947461, 0.24953231129767209),
 (0.1794076, 0.17942034065259632),
 (0.18237491, 0.18235826711360362),
 (0.19947933, 0.19955498210740999),
 (0.29338408, 0.29326234416036073)]
```

But maybe this issues is related to how I'm feeding this script to ```srun``` (because a lot of the 'info' output is repeatedly printed to the screen)?  Thoughts?  Help?

**Comment by moustakas** [comment] 2016-05-26 19:40
After reading a little more about SLURM, I tried 
```
salloc -N 1 -p debug -L project                                                                                                  
srun -n 1 -c 64 python bgs-sims.py --sim 4 --nproc 64 --zfind                                                                    
```
which seems to be better behaved in terms of info on just one brick at a time being printed out.  However, the ```zbest``` and input (```truth```) catalogs are still not row-aligned.

**Comment by sbailey** [comment] 2016-05-26 23:09
A few options for how to see if you are running out of memory on your laptop:
  * run `top` in a separate window while running the tests
  * `/usr/bin/time desi_zfind -n 1 --nproc 1 ...` will give a report for memory for a single target
  * if you have a mac, I find [iStat menus](https://bjango.com/mac/istatmenus/) to be super useful for keeping an eye on memory and CPU
  * if your whole machine slows to a crawl when running redmonster, that is another hint of getting low on memory and lots of swapping.  If the redmonster window is unresponsive but other windows are ok, then maybe not.

`zbest` and `ztruth` alignment:
* bricks have one row per spectrum, with possibly multiple spectra per targetid
* I think the truth HDUs (either in the brick or in a separate file) are row aligned to the spectra in the bricks, replicating the truth for the same object if it appears in multiple spectra
* ztruth only has one row per targetid, not per spectrum, thus it can't be guaranteed to be row aligned back to the original brick/truth file since it might have a different number of rows.

The current order is a side effect of `desispec.io.Brick.get_target_ids()` returning `list(set(self.hdu_list[4].data['TARGETID']))`  The `list(set(...))` operation loses the order of the input `TARGETID`s, even if they are unique and could be row matched to the original input.  That could be replaced with a few more lines of code that would return the TARGETIDs in the order that they appear in the input data.  But beware — do not trust that they are row matched because of the repeat spectra issue.  The current situation is a pain, but it might actually be better because it fails dramatically if you assume row matching rather than giving you a false sense of security and then subtly failing later when you have two spectra of some target...

i.e. this is a "feature" not a "bug", but it is a feature that is a pain that others have tripped over as well, so suggestions are welcome for how this could be made easier while still supporting the possibility of multiple spectra per target in a brick.

**Comment by tskisner** [comment] 2016-05-27 15:52
Sorry I'm late to this thread...  @moustakas , you are correct that for salloc / sbatch you just specify the number of nodes, then for srun you use options to control how processes are launched across those reserved nodes.  I just saw this similar "hang" for zfind during pipeline tests, launching one process per node (24 multiprocessing tasks per root process) on a single brick.  This operation did not finish in 2 hours, so I assume it was just hanging and not actually that slow.

I am going to try a couple quick things to see if I can find a case that works.

**Comment by tskisner** [comment] 2016-05-27 17:26
Another note:  python multiprocessing does not automatically know about the SLURM scheduler.  Instead it will try to use as many processes as there are cores it detects.  This means that when using the master branch of zfind at NERSC, you have to use 24 processes or manually limit the number with the --nproc argument.  Once I merge the pipe branch to master, this will be fixed to correctly only use the max cores per process allocated by slurm.  Here is the fix in the pipe branch:  https://github.com/desihub/desispec/commit/77fb1fd3c5d5a5dc9b8c7b29efea4fb92f79108e

We should implement a similar check for all codes in desi that use multiprocessing and which we intend to run at NERSC.  Maybe we could even put a helper function in desiutil or something.

**Comment by moustakas** [comment] 2016-05-28 22:37
Thank you, @tskisner, @sbailey.  

Update: I'm having a frustrating experience and I'm also still a little confused about how to best get the job done.  In my latest effort I dumped the 30-minute interactive queue and decided to submit a longer job.  The good news is that I haven't seen the multiprocessing hang (although I haven't gone back to my laptop.)  

I submitted the following batch script using ```sbatch```:
```
#!/bin/bash -l

#SBATCH -p regular
#SBATCH -N 1
#SBATCH -t 02:00:00
#SBATCH -L project
#SBATCH --mail-user jmoustakas@siena.edu

srun -n 1 -c 64 python ${HOME}/bgs-sims/bgs-sims.py --sim 4 --nproc 64 --zfind
```
First I tried a 1 hour reservation, then 1.5 hours, and right now I have a 2-hour reservation that's been in the queue for more than 24 hours.  Some thoughts and questions:
* @tskisner I'm confused about your statement about 24 processes.  [This website](http://www.nersc.gov/users/data-analytics/data-analytics/python/running-scripts/#toc-anchor-3) indicates that I should be able to make use of 32 cores and 32 hyperthreads (which I interpreted as ```nproc=64```) all within a single node.  Is this not correct?
* For the current code I'm trying to fit 50 spectra on 100 bricks.  In 1.5 hours the code only gets through ~70 bricks (hence the 2-hour reservation) and then times out.  (I know I could have just submitted the remaining 30 bricks, but I'm trying to come up with a set of parameters that will do many 100-brick simulated datasets without intervention.)  Does this mean that I need to wrap *my* code in the multiprocessing module and feed different subsets of my bricks to different nodes?  If so, how do I accomplish this in my ```sbatch``` script?
* The ```--mail-user``` option doesn't work.  Am I setting this up incorrectly or should I ask NERSC? It's frustrating to have to keep logging onto cori to check if the job is done (has started!).

I would appreciate any other suggestions for how to optimize this process. Or please let me know if this should come off Github and onto the mail list.

**Comment by tskisner** [comment] 2016-05-29 16:14
Hi @moustakas, I have only been using edison (24 physical cores).  In my experience with the zfind multiprocessing, running one process per physical core causes this hang.  In the pipeline, the set of bricks is distributed over some number of zfind "main processes", each of which then uses some number of multiprocessing processes which is smaller than 24 (because I am packing multiple zfind processes onto a node

Since you only have one master process, I think you should probably restrict the number of multiprocessing processes that are used to be smaller than the available cores.

I created a test slurm script for you here:

https://gist.github.com/tskisner/b8b0400b6312eb74b5504657f74b867a

This runs one master process and 8 multiprocessing processes on one node (8 is nice since it divides into 24 and 32, so this script works well on both edison and cori).

Let me know if that works...

**Comment by sbailey** [comment] 2016-07-12 22:47
I think this has been fixed via the parallelism updates in desihub/redmonster#1, our wrapper of redmonster in #232, and MPI wrappers for the full pipeline in #238.  I don't think we ever understood why the original multiprocessing wrapper wasn't working (it wasn't just a NERSC MPI+multiprocessing thing).  I'm going to close this ticket, but re-open or start a new issue if anyone has trouble with redmonster hanging with the latest code.

**Closed by sbailey** 2016-07-12 22:47 UTC
Labels: question

**Comment by rainwoodman** [comment] 2016-07-13 00:39
The unique function in numpy returns the indices to reconstruct the original with duplications. Just in case @sbailey wants the results to be row matched.
