### ISSUE TITLE
PROGRAM for TILEID=80866 unwisebluebright: bright vs. other

### ISSUE THREAD

**Issue by araichoor** [desihub/desispec#1690] opened 2022-02-16 05:17 UTC
This is a minor issue, but I'm reporting in case.
While checking the PROGRAM values in exposures-fuji.fits and tiles-fuji.csv, I notice that TILEID=80866 has `PROGRAM="bright"`.
Maybe we should set it to "other".

This tile has `FAPRGRM=unwisebluebright`, which explains why it gets PROGRAM set to bright:
https://github.com/desihub/desispec/blob/de07220f8e2ca729f71f1694f7abdce4a4abe345/py/desispec/io/meta.py#L585
However, this tile is part of a serie of those three tiles:
```
# TILEID SURVEY PROGRAM FAPRGRM
80865	sv1	other	unwisegreen
80866	sv1	bright	unwisebluebright
80867	sv1	other	unwisebluefaint
```

**Comment by sbailey** [comment] 2022-02-16 19:36
Thanks @araichoor for catching this.
I think this was an oversight and unwisebluebright was intended to be part of "other" instead of "bright".  I haven't found a written record of the original discussion but mentioning @djschlegel who helped craft the original mapping.  @djschlegel do you agree that unwisebluebright should be "other" instead of "bright", or was it purposefuly "bright", or do you think it doesn't matter?

This impacts sv1 healpix redshifts which are currently in the queue, so we need to get this sorted out ASAP.

**Comment by djschlegel** [comment] 2022-02-16 19:39
We would prefer this to be "other".

**Comment by sbailey** [comment] 2022-02-16 21:13
Thanks for the quick reply.  Action items for Fuji:
* `update desispec.io.meta.faflavor2program` to include the unwisebluebright -> other special case
* regenerate tiles and exposure summary files
* redo any bright and other healpix touched by unwisebluebright tile(s)

**Comment by sbailey** [comment] 2022-02-18 03:16
the exposures and tile files have been regenerated, and I removed the impacted healpix so that they will be re-generated as part of general missing healpix cleanup, so I'll close this ticket now.

**Closed by sbailey** 2022-02-18 03:16 UTC
