### ISSUE TITLE
MASK extensions of OAK1 frame/cframes/calib/sky files do not follow fits standard

### ISSUE THREAD

**Issue by cballand** [desihub/desispec#279] opened 2016-09-30 09:20 UTC
While trying to read frame/cframe/calib/sky files from the OAK1 production using c++ routines and HARP, I had the following crash:
```
terminate called after throwing an instance of 'harp::exception'
  what():  Exception at line 32 of file harp_fits.cpp:  cfitsio library error: 
TFIELDS keyword not found
Abort (core dumped)
```
The crash occurs because the TFIELDS card in the MASK tables is at the wrong place:

```python
In [1]: from astropy.io import fits
In [2]: cframe = fits.open('cframe-b0-00000006.fits')

In [4]: cframe['MASK'].verify()
WARNING: VerifyWarning: Output verification result: [astropy.io.fits.verify]
WARNING: VerifyWarning: 'TFIELDS' card at the wrong place (card 9). [astropy.io.fits.verify]
WARNING: VerifyWarning: Note: Astropy uses zero-based indexing.
 [astropy.io.fits.verify]
```
This can easily be fixed:

```python
In [5]: cframe['MASK'].verify('fix')
WARNING: VerifyWarning: 'TFIELDS' card at the wrong place (card 9).  
Fixed by moving it to the right place (card 7). [astropy.io.fits.verify]
```
but it should be corrected when writing the  MASK extension in the frame/cframe/calib.sky files.

**Comment by sbailey** [comment] 2016-10-12 04:25
This was caused by a bug that has been fixed in astropy 1.2.1 (see astropy/astropy#5118), but oak was using astropy 1.1.1.  astropy 1.2.1 is our new default so we won't have this problem for future runs.  I won't retroactively fix the oak files but it's good to know that someone could use the trick @cballand included in the report if they need to locally download the oak files and fix them for work with C++ or fitsio.

**Closed by sbailey** 2016-10-12 04:25 UTC
Labels: bug
