### ISSUE TITLE
Flux calibration for low S/N exposures

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#1019] opened 2020-11-03 19:43 UTC
At test in PR #1014 has shown that the flux calibration is failing for exposures with very low transmission.

**Comment by sbailey** [comment] 2020-12-22 19:10
I think this is a duplicate of #1018 and was fixed in #1059.  Reopen with a clarification comment if that isn't correct.

**Closed by sbailey** 2020-12-22 19:10 UTC
Labels: enhancement
