### ISSUE TITLE
No z_* extensions in coadd- or spectra- file

### ISSUE THREAD

**Issue by jacquesalice** [desihub/desispec#1303] opened 2021-06-11 23:20 UTC
The following files are missing all z-band extensions (z_wavelength, z_flux, z_ivar, z_mask, z_resolution):

`/denali/tiles/cumulative/80724/20210328/coadd-7-80724-thru20210328.fits`
`/denali/tiles/cumulative/80724/20210328/spectra-7-80724-thru20210328.fits`

Instead, the coadd file only has:
```
Filename: /denali/tiles/cumulative/80724/20210328/coadd-7-80724-thru20210328.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      38   ()      
  1  FIBERMAP      1 BinTableHDU    192   500R x 90C   [K, I, J, K, J, J, D, D, E, E, E, E, K, B, 3A, J, D, J, I, J, J, 4A, E, E, E, E, E, E, I, K, 2A, E, E, E, E, 8A, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, 1A, K, K, K, K, K, K, K, K, K, D, J, I, E, E, E, E, E, E, E, D, D, E, E, J, J, I, J, J, I, J, J, I, J, J, I, E, E, I]   
  2  B_WAVELENGTH    1 ImageHDU        10   (2751,)   float64   
  3  B_FLUX        1 ImageHDU        11   (2751, 500)   float32   
  4  B_IVAR        1 ImageHDU        11   (2751, 500)   float32   
  5  B_MASK        1 ImageHDU        12   (2751, 500)   int32 (rescales to uint32)   
  6  B_RESOLUTION    1 ImageHDU        11   (2751, 11, 500)   float32   
  7  R_WAVELENGTH    1 ImageHDU        10   (2326,)   float64   
  8  R_FLUX        1 ImageHDU        11   (2326, 500)   float32   
  9  R_IVAR        1 ImageHDU        11   (2326, 500)   float32   
 10  R_MASK        1 ImageHDU        12   (2326, 500)   int32 (rescales to uint32)   
 11  R_RESOLUTION    1 ImageHDU        11   (2326, 11, 500)   float32   
 12  SCORES        1 BinTableHDU     56   500R x 22C   [K, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E] 
```

And the spectra file only has:
```
Filename: /denali/tiles/cumulative/80724/20210328/spectra-7-80724-thru20210328.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      36   ()      
  1  FIBERMAP      1 BinTableHDU    163   500R x 76C   [K, I, J, K, J, J, D, D, E, E, E, E, K, B, 3A, E, E, J, D, J, I, J, J, 4A, E, E, E, E, E, E, I, K, 2A, E, E, E, E, 8A, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, 1A, K, K, K, K, K, K, K, K, K, K, D, D, D, D, D, D, D, D, J, J, D, J]   
  2  SCORES        1 BinTableHDU     77   500R x 34C   [D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D]   
  3  B_WAVELENGTH    1 ImageHDU         8   (2751,)   float64   
  4  B_FLUX        1 ImageHDU         9   (2751, 500)   float32   
  5  B_IVAR        1 ImageHDU         9   (2751, 500)   float32   
  6  B_MASK        1 CompImageHDU     10   (2751, 500)   int32   
  7  B_RESOLUTION    1 ImageHDU         9   (2751, 11, 500)   float32   
  8  R_WAVELENGTH    1 ImageHDU         8   (2326,)   float64   
  9  R_FLUX        1 ImageHDU         9   (2326, 500)   float32   
 10  R_IVAR        1 ImageHDU         9   (2326, 500)   float32   
 11  R_MASK        1 CompImageHDU     10   (2326, 500)   int32   
 12  R_RESOLUTION    1 ImageHDU         9   (2326, 11, 500)   float32   
```

These are the only 2 files in denali that do not have all 18 HDUs.

**Comment by weaverba137** [comment] 2021-07-27 16:41
@sbailey, this does not appear to have been addressed in everest.  If it is impossible to recover the Z HDUs, this data model violation should at least be documented.

**Comment by stephjuneau** [comment] 2021-09-03 02:43
Question related to this issue: How are such files missing a camera handled by `coadd_cameras`? (https://desispec.readthedocs.io/en/stable/api.html?highlight=coadd_across_camera#desispec.coaddition.coadd_cameras)

**Comment by sbailey** [comment] 2021-09-09 03:19
Originally this was intended as a feature: the spectra files are containers of spectra, without any datamodel-imposed constraints on what cameras are supposed to be there.  If an exposure only has B and R but not Z, ok, the spectra files reflect that.  The exception was that if a single camera was missing from some but not all exposures, rows for that exposure for that camera would be zero-padded so that the *_FLUX, *_IVAR, FIBERMAP, etc. HDUs remain row-matched.  But if all exposures were missing a given camera, then it just wouldn't be represented.

`desispec.coaddition.coadd_cameras` works with this, coadding whatever cameras it can find.  The `Spectra` object returned by `desispec.io.read_spectra` has a member variable `spectra.bands` which contains the list of cameras present.

However, if a camera is completely missing from all input exposures, the flux calibration (and redshift fits!) for those spectra won't be as reliable and they shouldn't have made it into the output spectra files in the first place.  I'm pretty sure that the updated camera bookkeeping in PR #1402 will now prevent cases like this, but I will leave this ticket open until confirmed.

Cases in everest where tile-based spectra are missing a camera:
```
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/cumulative/1821/20210616/spectra-9-1821-thru20210616.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/cumulative/1823/20210616/spectra-9-1823-thru20210616.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/cumulative/1841/20210616/spectra-9-1841-thru20210616.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/cumulative/1843/20210616/spectra-9-1843-thru20210616.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/cumulative/1892/20210616/spectra-9-1892-thru20210616.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/cumulative/20885/20210616/spectra-9-20885-thru20210616.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/cumulative/20886/20210616/spectra-9-20886-thru20210616.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/cumulative/20890/20210616/spectra-9-20890-thru20210616.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/cumulative/20910/20210616/spectra-9-20910-thru20210616.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/cumulative/313/20210417/spectra-8-313-thru20210417.fits missing Z_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/cumulative/314/20210420/spectra-2-314-thru20210420.fits missing Z_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/cumulative/314/20210420/spectra-6-314-thru20210420.fits missing Z_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/perexp/1821/00094987/spectra-9-1821-exp00094987.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/perexp/1823/00094988/spectra-9-1823-exp00094988.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/perexp/1841/00094986/spectra-9-1841-exp00094986.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/perexp/1843/00094985/spectra-9-1843-exp00094985.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/perexp/1892/00094983/spectra-9-1892-exp00094983.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/perexp/1892/00094984/spectra-9-1892-exp00094984.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/perexp/20885/00094981/spectra-9-20885-exp00094981.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/perexp/20886/00094980/spectra-9-20886-exp00094980.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/perexp/20890/00094982/spectra-9-20890-exp00094982.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/perexp/20910/00094979/spectra-9-20910-exp00094979.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/perexp/313/00085210/spectra-8-313-exp00085210.fits missing Z_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/perexp/314/00085636/spectra-2-314-exp00085636.fits missing Z_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/perexp/314/00085636/spectra-6-314-exp00085636.fits missing Z_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/perexp/341/00085635/spectra-4-341-exp00085635.fits missing Z_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/pernight/1821/20210616/spectra-9-1821-20210616.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/pernight/1823/20210616/spectra-9-1823-20210616.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/pernight/1841/20210616/spectra-9-1841-20210616.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/pernight/1843/20210616/spectra-9-1843-20210616.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/pernight/1892/20210616/spectra-9-1892-20210616.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/pernight/20885/20210616/spectra-9-20885-20210616.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/pernight/20886/20210616/spectra-9-20886-20210616.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/pernight/20890/20210616/spectra-9-20890-20210616.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/pernight/20910/20210616/spectra-9-20910-20210616.fits missing R_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/pernight/313/20210417/spectra-8-313-20210417.fits missing Z_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/pernight/314/20210420/spectra-2-314-20210420.fits missing Z_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/pernight/314/20210420/spectra-6-314-20210420.fits missing Z_FLUX
/global/cfs/cdirs/desi/spectro/redux/everest/tiles/pernight/341/20210420/spectra-4-341-20210420.fits missing Z_FLUX
```

**Comment by sbailey** [comment] 2021-09-09 03:21
I spot checked some of these and confirmed that current desispec master will refuse to flux calibrate spectrographs where a camera is missing from all input exposures, and thus cases like this will not make it into the output spectra for future productions.  Closing.

**Closed by sbailey** 2021-09-09 03:21 UTC
