### ISSUE TITLE
ELG redshift failures due to bad sky model

### ISSUE THREAD

**Issue by Jiaxi-Yu** [desihub/desispec#2152] opened 2023-12-29 15:06 UTC
![OII_sky_confusion](https://github.com/desihub/desispec/assets/53114060/ddc7b41d-f445-4651-8461-2d70ef95f63f)
[desispec_ELG_failure.txt](https://github.com/desihub/desispec/files/13794406/desispec_ELG_failure.txt)
The attached figure is a typical ELG spectrum that was identified as a redshift catastrophic failure. The [OII] vertical dashed lines are at the correct position determined by visual inspection. The black line is the Redrock redshift, which misidentified the sky residual as [OII] doublets. This comprises 20% of the total catastrophic failure (<0.3% for EDR and Y1). 
As the CTE problem has been solved (Stephen at the Hawaii meeting in 2024), shall we expect a suppressed sky-residual ELG redshift failure rate? 
The attached ASCII file is a list of ELG catastrophic failures identified in daily samples (by comparing with SV3 redshifts) for your reference. Both use iron redrock.

**Comment by sbailey** [comment] 2024-01-02 19:08
@Jiaxi-Yu thanks.  Could you also provide the table with incorrect redshifts and correct redshifts for these targets?  It's unclear to me whether the CTE problems/fixes explain these cases, but this is a useful set for testing.

@dylanagreen @moustakas @abrodze @abhi0395 heads up for the "is Redrock correct" group.

**Comment by araichoor** [comment] 2024-01-07 04:24
thanks @Jiaxi-Yu for sharing infos.

for what is worth, I ve spot-checked few cases: my understanding is that, for those cases, there always are 1-2 pixels around 8660A which have an insanely large snr, like >15.

i.e. another way to phrase the issue is that the flux error is severely underestimated for those pixels.
though I don t know if there is a way to improve that in the processing, as those pixels around sky emission lines are very hard to handle.

here s one example for `TARGETID=39627444868617702` (same target as in the prospect screenshot in the initial message):
![tmp1](https://github.com/desihub/desispec/assets/61986357/e89db548-fc89-4d66-876f-c9536d346f8d)

**Comment by moustakas** [comment] 2024-03-15 12:37
I only checked this first object, but the good news is that the new (non-negative, physical) galaxy templates get the right redshift (in fact, the top three minima are at the right redshift, just with different galaxy subtypes and comparable chi2):

![image](https://github.com/desihub/desispec/assets/1431820/e029bb1e-71bd-44ad-8aab-3f32dfc5c53a)

**Comment by moustakas** [comment] 2024-04-25 00:44
@Jiaxi-Yu I'm going to close this ticket but I've ported it over to https://github.com/desihub/rrevaluator/issues/4, where we're consolidating all the various "is Redrock right or wrong" tickets which are currently spread across many different repositories.

We should have a more substantive update for you regarding this issue soon.

**Closed by moustakas** 2024-04-25 00:44 UTC
