### ISSUE TITLE
Implement incremental daily processing scripts

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#445] opened 2017-10-10 22:03 UTC
This is a follow-on to issue #322, to flesh out the scripts used for daily processing of data.  These will be called by the data transfer system as new data arrive.
* `desi_start_night`: afternoon calibrations have finished; launch jobs to process those to generate the PSF and fiberflat data for the night.
* `desi_update_night`: a new science exposure has arrived; launch jobs to process it through calibrated frames
* `desi_end_night`: All science exposures have been received; launch jobs to reorganized calibrated frames into grouped-on-the-sky-by-healpix spectra files and launch redshift fitting on any that have changed.  Update spectra meta DB.  Run nightly QA.

In the process of implementing and using these, we may learn more about what exactly is needed (e.g. do we need something to trigger the start of afternoon calibrations, or is it sufficient to let them all arrive and then trigger processing them all together via `desi_start_night`).

A significant goal of these is to get a head start on the spectral extractions as the data arrive instead of waiting for everything to arrive before processing any of this.  This should enable starting redshift fitting shortly after sunrise and having updated results before lunch.

**Comment by tskisner** [comment] 2017-11-01 14:26
Duplicate of #304.  I'm going to close this and add your comments above to that issue.

**Closed by tskisner** 2017-11-01 14:26 UTC
