### ISSUE TITLE
Fuji: no stdstars selected tile 97 sp7 20210418 exp 85343

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1646] opened 2022-02-02 18:47 UTC
desi_select_calib_stars didn't select any standard stars for 20210418 exp 85343 sp7 in Fuji though I don't immediately see why (and it was processed find in everest and daily before we were using desi_select_calib_stars).  @julienguy can you check whether we should flag this petal as bad or otherwise what is wrong?  Thanks.

**Comment by julienguy** [comment] 2022-02-02 19:57
- There is only 1 fitted std star in SP7 for this exposure (so the data is discarded at the QA level anyway).
- In fuji its difference of g-r color between data and model is 0.11.
- In everest the same difference of g-r color between data and model is 0.07.
There is cut on this g-r difference between data and model at 0.1, so no star is left in Fuji.
This is not a bug. I think we should close the issue.

**Comment by akremin** [comment] 2022-02-02 21:35
That change in g-r is due to valid improvements in the pipeline rather than a new issue introduced? 
i.e. you're happy with the fit that led to the cut?

Once you confirm the above I will happily remove the petal and close the ticket.

**Comment by julienguy** [comment] 2022-02-02 21:42
There is no evidence of a new issue. We changed many things to the pipeline
since everest, it's easy to imagine they can result in a change of 3%.

**Comment by akremin** [comment] 2022-02-02 23:09
I removed all sp7 spectra from this exposure for good measure. 

I flagged the bad petal with the following:
`desi_edit_exposure_table -n 20210418 -e 85343 -c BADCAMWORD -v a7 --append-string --include-comment="No valid stdstar on p7"`

Then removed the relevant jobs from the processing table and reran the tile with:
`NIGHT=20210418; desi_run_night -n ${NIGHT} --tiles="97" --system-name="cori-knl" --append-to-proc-table &>>${DESI_SPECTRO_REDUX}/${SPECPROD}/logs/${NIGHT}.log &`

**Closed by akremin** 2022-02-02 23:09 UTC
